// Auto-generated by Tour Editor
const START_SCENE = "a0_gate";
const SCENES = {
  "ar/1BM.jpg": {
    "pano": "ar/1BM.jpg",
    "label": "First Floor Lobby",
    "audio": "",
    "arrows": [
      {
        "pitch": -8.063907000923546,
        "yaw": -42.01466513973864,
        "next": "ar/1B-1.jpg"
      },
      {
        "pitch": -7.656826095670738,
        "yaw": -144.41341339710883,
        "next": "ar/1A-1.jpg"
      },
      {
        "pitch": -6.770067112383427,
        "yaw": 139.6950006332718,
        "next": "ar/1A1.jpg"
      },
      {
        "pitch": -0.00724873199025026,
        "yaw": -116.47706267442042,
        "next": "ar/2BM.jpg"
      },
      {
        "pitch": -8.526022310070864,
        "yaw": 39.38437706632958,
        "next": "ar/First Floor (20).jpg"
      },
      {
        "pitch": -12.556002360562088,
        "yaw": -67.45591079161309,
        "next": "a0_block_bm",
        "label": "Go Down to Ground Floor"
      }
    ]
  },
  "ar/1B-1.jpg": {
    "pano": "ar/1B-1.jpg",
    "label": "First Floor B Block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -13.881908716309189,
        "yaw": -94.33951241999054,
        "next": "ar/1BM.jpg"
      },
      {
        "pitch": -4.068339633809019,
        "yaw": 179.79185536993168,
        "next": "ar/1BC-1.jpg"
      },
      {
        "pitch": -9.773181475679724,
        "yaw": -0.9040752882225145,
        "next": "ar/1A-1.jpg"
      },
      {
        "pitch": -5.75936223864084,
        "yaw": 93.80599581600026,
        "next": "ar/First Floor (23).jpg"
      }
    ]
  },
  "ar/1BC-1.jpg": {
    "pano": "ar/1BC-1.jpg",
    "label": "First Floor B C block Bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -10.476343118911164,
        "yaw": 90.56627853823991,
        "next": "ar/1B-1.jpg"
      },
      {
        "pitch": -7.002952177609041,
        "yaw": -89.75852914486981,
        "next": "ar/First floor (21).jpg"
      }
    ]
  },
  "ar/1A-1.jpg": {
    "pano": "ar/1A-1.jpg",
    "label": "First Floor A Block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -12.213555790489227,
        "yaw": -2.274885551309415,
        "next": "ar/1B-1.jpg"
      },
      {
        "pitch": -14.034398748184543,
        "yaw": 90.35070748496987,
        "next": "ar/1BM.jpg"
      },
      {
        "pitch": -1.3950191773791152,
        "yaw": -90.8365985049037,
        "next": "ar/1A-3.jpg"
      }
    ]
  },
  "ar/1A1.jpg": {
    "pano": "ar/1A1.jpg",
    "label": "First Floor A Block Right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -17.465453674056327,
        "yaw": -178.40351103931377,
        "next": "ar/1BM.jpg"
      },
      {
        "pitch": -0.10664774362585053,
        "yaw": 1.6354893807871855,
        "next": "ar/1A2.jpg"
      },
      {
        "pitch": -5.876512868047868,
        "yaw": -89.43533022773629,
        "next": "ar/First Floor (20).jpg"
      }
    ]
  },
  "ar/1A2.jpg": {
    "pano": "ar/1A2.jpg",
    "label": "First Floor A Block Right middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -3.7250064888280345,
        "yaw": -2.629871038624652,
        "next": "ar/1A1.jpg"
      },
      {
        "pitch": -3.0960831399350606,
        "yaw": -179.8311384270334,
        "next": "ar/First Floor (22).jpg"
      }
    ]
  },
  "ar/1A-3.jpg": {
    "pano": "ar/1A-3.jpg",
    "label": "First Floor A Block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -2.5988624614833795,
        "yaw": 94.38126378403122,
        "next": "ar/1A-1.jpg"
      },
      {
        "pitch": -5.465991107480246,
        "yaw": -1.3259840564820704,
        "next": "ar/First Floor (24).jpg"
      }
    ]
  },
  "ar/1BC1.jpg": {
    "pano": "ar/1BC1.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -4.319695839727961,
        "yaw": -2.345157930388642,
        "next": "ar/1A-3.jpg"
      }
    ]
  },
  "ar/2BM.jpg": {
    "pano": "ar/2BM.jpg",
    "label": "Second Floor Lobby",
    "audio": "",
    "arrows": [
      {
        "pitch": -5.052759153086717,
        "yaw": 37.2705660718831,
        "next": "ar/Second Floor (11).jpg"
      },
      {
        "pitch": -4.956665432469318,
        "yaw": -42.66282225424898,
        "next": "ar/Second Floor (14).jpg"
      },
      {
        "pitch": -4.829872262678508,
        "yaw": 139.33137784837422,
        "next": "ar/Second Floor (15).jpg"
      },
      {
        "pitch": -3.8980057078426396,
        "yaw": -138.0485782894753,
        "next": "ar/Second Floor (16).jpg"
      },
      {
        "pitch": -9.620789684360528,
        "yaw": 111.37034012678858,
        "next": "ar/1BM.jpg"
      },
      {
        "pitch": 2.9187415310227056,
        "yaw": 64.60304710513385,
        "next": "ar/Third Floor (19).jpg"
      }
    ]
  },
  "ar/Second Floor (11).jpg": {
    "pano": "ar/Second Floor (11).jpg",
    "label": "Second Floor A block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -10.71866817210213,
        "yaw": 2.607083054646317,
        "next": "ar/Second Floor (10).jpg"
      },
      {
        "pitch": -14.415952290301584,
        "yaw": -175.29102841689826,
        "next": "ar/2BM.jpg"
      },
      {
        "pitch": -8.03135978759748,
        "yaw": 95.59297633102082,
        "next": "ar/Second Floor (15).jpg"
      }
    ]
  },
  "ar/Second Floor (10).jpg": {
    "pano": "ar/Second Floor (10).jpg",
    "label": "Second Floor A Block Left middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -9.002279041497872,
        "yaw": 178.9238987889335,
        "next": "ar/Second Floor (11).jpg"
      },
      {
        "pitch": -9.337420249458477,
        "yaw": -0.7233912932715416,
        "next": "ar/Second Floor (9).jpg"
      }
    ]
  },
  "ar/Second Floor (8).jpg": {
    "pano": "ar/Second Floor (8).jpg",
    "label": "Second Floor A Block right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -3.7268357998473434,
        "yaw": -1.9197252395945514,
        "next": "ar/Second Floor (12).jpg"
      },
      {
        "pitch": -8.16602935850906,
        "yaw": 91.32057106985484,
        "next": "ar/Second Floor (25).jpg"
      }
    ]
  },
  "ar/Second Floor (9).jpg": {
    "pano": "ar/Second Floor (9).jpg",
    "label": "Second Floor A Block left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 0,
        "next": "ar/Second Floor (8).jpg"
      },
      {
        "pitch": -3.751697996666263,
        "yaw": -90.9234571878099,
        "next": "ar/Second Floor (5).jpg"
      }
    ]
  },
  "ar/Second Floor (14).jpg": {
    "pano": "ar/Second Floor (14).jpg",
    "label": "Second Floor A Block right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -20.455170411837997,
        "yaw": -107.58430775280821,
        "next": "ar/2BM.jpg"
      },
      {
        "pitch": -3.4434523554265413,
        "yaw": -1.9907699841965742,
        "next": "ar/Second Floor (16).jpg"
      },
      {
        "pitch": -5.8103230250692635,
        "yaw": 92.26599227099112,
        "next": "ar/Second Floor (12).jpg"
      }
    ]
  },
  "ar/Second Floor (15).jpg": {
    "pano": "ar/Second Floor (15).jpg",
    "label": "Second Floor B Block left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -14.5077561635569,
        "yaw": -1.351172979007308,
        "next": "ar/2BM.jpg"
      },
      {
        "pitch": -6.481550048725279,
        "yaw": 94.87592553568595,
        "next": "ar/Second Floor (11).jpg"
      },
      {
        "pitch": -6.879009407233729,
        "yaw": -177.33886211211885,
        "next": "ar/Second Floor (7).jpg"
      },
      {
        "pitch": -2.4121692489480524,
        "yaw": -82.59702746110773,
        "next": "ar/Second Floor (13).jpg"
      }
    ]
  },
  "ar/Second Floor (16).jpg": {
    "pano": "ar/Second Floor (16).jpg",
    "label": "Second Floor B Block right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -16.719298323400487,
        "yaw": -82.74666080439613,
        "next": "ar/2BM.jpg"
      },
      {
        "pitch": -2.853965804535322,
        "yaw": 88.68473235279724,
        "next": "ar/Second Floor (23).jpg"
      },
      {
        "pitch": -0.46222789548844023,
        "yaw": -1.1378912262236394,
        "next": "ar/Second Floor (17).jpg"
      },
      {
        "pitch": -1.4777290031063088,
        "yaw": 179.86560887274936,
        "next": "ar/Second Floor (14).jpg"
      }
    ]
  },
  "ar/Second Floor (20).jpg": {
    "pano": "ar/Second Floor (20).jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -4.28737982477375,
        "yaw": -127.86745791786933,
        "next": "ar/Second Floor (16).jpg"
      }
    ]
  },
  "ar/Second Floor (23).jpg": {
    "pano": "ar/Second Floor (23).jpg",
    "label": "Second Floor B Block right middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 0,
        "next": "ar/Second Floor (16).jpg"
      },
      {
        "pitch": -7.040244117234454,
        "yaw": -177.07208452536216,
        "next": "ar/Second Floor (25).jpg"
      }
    ]
  },
  "ar/Second Floor (25).jpg": {
    "pano": "ar/Second Floor (25).jpg",
    "label": "Second Floor B Block right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 0,
        "next": "ar/Second Floor (23).jpg"
      },
      {
        "pitch": -16.157493753874526,
        "yaw": 90.4354506705938,
        "next": "ar/Second Floor (22).jpg"
      },
      {
        "pitch": -6.728426295566079,
        "yaw": -94.3282376271253,
        "next": "ar/Second Floor (8).jpg"
      }
    ]
  },
  "ar/Second Floor (22).jpg": {
    "pano": "ar/Second Floor (22).jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 0,
        "next": "ar/Second Floor (19).jpg"
      },
      {
        "pitch": -4.683780053295438,
        "yaw": -179.94572218848737,
        "next": "ar/Second Floor (25).jpg"
      }
    ]
  },
  "ar/Second Floor (19).jpg": {
    "pano": "ar/Second Floor (19).jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -1.083428860509609,
        "yaw": -91.65225039162704,
        "next": "ar/Second Floor (22).jpg"
      },
      {
        "pitch": -7.664026431503053,
        "yaw": 2.4878995590928934,
        "next": "ar/Second Floor (18).jpg"
      }
    ]
  },
  "ar/Second Floor (18).jpg": {
    "pano": "ar/Second Floor (18).jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -4.730949221241901,
        "yaw": 179.51220072599165,
        "next": "ar/Second Floor (19).jpg"
      },
      {
        "pitch": -1.8840555734135593,
        "yaw": -0.7112389972166203,
        "next": "ar/Second Floor (17).jpg"
      }
    ]
  },
  "ar/Second Floor (17).jpg": {
    "pano": "ar/Second Floor (17).jpg",
    "label": "Second Floor A and C block bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 0,
        "next": "ar/Second Floor (18).jpg"
      },
      {
        "pitch": -3.502195484235393,
        "yaw": 91.27204354048827,
        "next": "ar/Second Floor (16).jpg"
      }
    ]
  },
  "ar/Second Floor (12).jpg": {
    "pano": "ar/Second Floor (12).jpg",
    "label": "Second Floor A Block right middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -2.5934154277345622,
        "yaw": -1.5644172857988528,
        "next": "ar/Second Floor (14).jpg"
      },
      {
        "pitch": -4.48330460315646,
        "yaw": 179.60290114078666,
        "next": "ar/Second Floor (8).jpg"
      }
    ]
  },
  "ar/Second Floor (5).jpg": {
    "pano": "ar/Second Floor (5).jpg",
    "label": "Second Floor B Block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -7.600986793831071,
        "yaw": 90.23709628312558,
        "next": "ar/Second Floor (9).jpg"
      },
      {
        "pitch": -1.904163373712665,
        "yaw": -1.158488004221705,
        "next": "ar/Second Floor (7).jpg"
      },
      {
        "pitch": -12.283475301903335,
        "yaw": -93.88789279195902,
        "next": "ar/Second Floor (6).jpg"
      }
    ]
  },
  "ar/Second Floor (7).jpg": {
    "pano": "ar/Second Floor (7).jpg",
    "label": "Second Floor B Block left middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -4.889911048178138,
        "yaw": -5.524128330704506,
        "next": "ar/Second Floor (5).jpg"
      },
      {
        "pitch": -1.3224198419947024,
        "yaw": -178.15247187246183,
        "next": "ar/Second Floor (15).jpg"
      }
    ]
  },
  "ar/Second Floor (6).jpg": {
    "pano": "ar/Second Floor (6).jpg",
    "label": "Second Floor B and C block Bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 0,
        "next": "ar/Second Floor (5).jpg"
      },
      {
        "pitch": -5.917648565627489,
        "yaw": -176.75481205141136,
        "next": "ar/Second Floor (4).jpg"
      }
    ]
  },
  "ar/Second Floor (4).jpg": {
    "pano": "ar/Second Floor (4).jpg",
    "label": "Second Floor C  Block left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -0.6986356986505563,
        "yaw": 86.64817692748575,
        "next": "ar/Second Floor (6).jpg"
      },
      {
        "pitch": -6.17706560985223,
        "yaw": -1.8779496347135876,
        "next": "ar/Second Floor (3).jpg"
      }
    ]
  },
  "ar/Second Floor (3).jpg": {
    "pano": "ar/Second Floor (3).jpg",
    "label": "Second Floor C Block left middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -4.336128311245379,
        "yaw": -0.6218801729690302,
        "next": "ar/Second Floor (4).jpg"
      },
      {
        "pitch": -4.900106846277595,
        "yaw": 178.18205443817573,
        "next": "ar/Second Floor (2).jpg"
      }
    ]
  },
  "ar/Second Floor (2).jpg": {
    "pano": "ar/Second Floor (2).jpg",
    "label": "Second Floor C Block left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -7.3036032977173795,
        "yaw": -0.05865984626275811,
        "next": "ar/Second Floor (3).jpg"
      },
      {
        "pitch": -2.882139236884393,
        "yaw": -89.7459132053504,
        "next": "ar/Second Floor (13).jpg"
      }
    ]
  },
  "ar/Second Floor (13).jpg": {
    "pano": "ar/Second Floor (13).jpg",
    "label": "Second Floor A and C block Bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 0,
        "next": "ar/Second Floor (2).jpg"
      },
      {
        "pitch": -7.757331843197335,
        "yaw": -177.02647715567014,
        "next": "ar/Second Floor (15).jpg"
      }
    ]
  },
  "ar/Third Floor (19).jpg": {
    "pano": "ar/Third Floor (19).jpg",
    "label": "Third Floor PRR Hall",
    "audio": "",
    "arrows": [
      {
        "pitch": -4.717137296698215,
        "yaw": 137.8152682204597,
        "next": "ar/Third Floor (14).jpg"
      },
      {
        "pitch": -6.035174772129677,
        "yaw": -143.6212311778942,
        "next": "ar/Third Floor (10).jpg"
      },
      {
        "pitch": -9.18789833359114,
        "yaw": 116.07166625314703,
        "next": "ar/2BM.jpg"
      },
      {
        "pitch": -6.008772279313684,
        "yaw": -94.27278502300223,
        "next": "ar/Fourth Floor (2).jpg"
      },
      {
        "pitch": 0.790619021269468,
        "yaw": 65.54800495981492,
        "next": "ar/Fourth Floor (4).jpg"
      }
    ]
  },
  "ar/Third Floor (10).jpg": {
    "pano": "ar/Third Floor (10).jpg",
    "label": "Third Floor B Block right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -17.8246287625484,
        "yaw": -142.10459679901504,
        "next": "ar/Third Floor (19).jpg"
      },
      {
        "pitch": -8.3900981401941,
        "yaw": -44.06394718845293,
        "next": "ar/Third Floor (11).jpg"
      },
      {
        "pitch": -3.919906397213936,
        "yaw": 36.31271374163376,
        "next": "ar/Third Floor (9).jpg"
      }
    ]
  },
  "ar/Third Floor (11).jpg": {
    "pano": "ar/Third Floor (11).jpg",
    "label": "Third Floor B and C bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -12.698090663507314,
        "yaw": -179.28757184932707,
        "next": "ar/Third Floor (10).jpg"
      },
      {
        "pitch": -6.63462290487808,
        "yaw": -1.7006990547518472,
        "next": "ar/Third Floor (12).jpg"
      }
    ]
  },
  "ar/Third Floor (12).jpg": {
    "pano": "ar/Third Floor (12).jpg",
    "label": "Third Floor C Block right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -7.314311498623831,
        "yaw": 83.29246967807516,
        "next": "ar/Third Floor (11).jpg"
      },
      {
        "pitch": -4.319017016943764,
        "yaw": -9.16344213314035,
        "next": "ar/Third Floor (7).jpg"
      }
    ]
  },
  "ar/Third Floor (14).jpg": {
    "pano": "ar/Third Floor (14).jpg",
    "label": "Third Floor B Block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -23.56719152066145,
        "yaw": -149.94370026779524,
        "next": "ar/Third Floor (19).jpg"
      },
      {
        "pitch": -2.390646084413869,
        "yaw": 109.5601437058667,
        "next": "ar/Third Floor (15).jpg"
      },
      {
        "pitch": -7.373922861242323,
        "yaw": -2.1251538060190134,
        "next": "ar/Third Floor (2).jpg"
      }
    ]
  },
  "ar/Third Floor (15).jpg": {
    "pano": "ar/Third Floor (15).jpg",
    "label": "THird Floor B and C block Bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -7.530579355280026,
        "yaw": -0.8534675088447927,
        "next": "ar/Third Floor (16).jpg"
      },
      {
        "pitch": -6.97917645355342,
        "yaw": 177.606721560133,
        "next": "ar/Third Floor (14).jpg"
      }
    ]
  },
  "ar/Third Floor (9).jpg": {
    "pano": "ar/Third Floor (9).jpg",
    "label": "Third Floor B Block right middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -4.090596584411388,
        "yaw": -1.5075688394434152,
        "next": "ar/Third Floor (10).jpg"
      },
      {
        "pitch": -2.34179343691248,
        "yaw": -176.8539494349426,
        "next": "ar/Third Floor (13).jpg"
      }
    ]
  },
  "ar/Third Floor (3).jpg": {
    "pano": "ar/Third Floor (3).jpg",
    "label": "Third Floor B Block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -4.05973730778115,
        "yaw": 99.06220287454188,
        "next": "ar/Third Floor (2).jpg"
      },
      {
        "pitch": -14.484787525440739,
        "yaw": -167.96840919691834,
        "next": "ar/Third Floor (1).jpg"
      },
      {
        "pitch": -3.7189888200397405,
        "yaw": 4.189045522887569,
        "next": "ar/Third Floor (5).jpg"
      }
    ]
  },
  "ar/Third Floor (8).jpg": {
    "pano": "ar/Third Floor (8).jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -12.101405339411794,
        "yaw": -171.81968040863478,
        "next": "ar/Third Floor (5).jpg"
      }
    ]
  },
  "ar/Third Floor (2).jpg": {
    "pano": "ar/Third Floor (2).jpg",
    "label": "Third Floor B Block Left Middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -6.039984987057049,
        "yaw": -5.674287068370823,
        "next": "ar/Third Floor (3).jpg"
      },
      {
        "pitch": -5.823788658198411,
        "yaw": -167.78884337419152,
        "next": "ar/Third Floor (14).jpg"
      }
    ]
  },
  "ar/Third Floor (1).jpg": {
    "pano": "ar/Third Floor (1).jpg",
    "label": "Third Floor B Block Drawing Hall",
    "audio": "",
    "arrows": [
      {
        "pitch": -12.838843591505476,
        "yaw": -88.71895824596567,
        "next": "ar/Third Floor (3).jpg"
      }
    ]
  },
  "ar/Third Floor (5).jpg": {
    "pano": "ar/Third Floor (5).jpg",
    "label": "THird Floor B and C block Bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 0,
        "next": "ar/Third Floor (3).jpg"
      },
      {
        "pitch": -8.001674054262658,
        "yaw": 176.0886732734397,
        "next": "ar/Third Floor (20).jpg"
      }
    ]
  },
  "ar/Third Floor (16).jpg": {
    "pano": "ar/Third Floor (16).jpg",
    "label": "Third Floor C block Left Middle",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 0,
        "next": "ar/Third Floor (20).jpg"
      },
      {
        "pitch": -1.7991744368175415,
        "yaw": 178.1089203661664,
        "next": "ar/Third Floor (15).jpg"
      }
    ]
  },
  "ar/Third Floor (13).jpg": {
    "pano": "ar/Third Floor (13).jpg",
    "label": "Third Floor B Block right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -8.740964356760726,
        "yaw": -95.50416118600707,
        "next": "ar/Third Floor (9).jpg"
      },
      {
        "pitch": -5.200955576718927,
        "yaw": -3.97674483044396,
        "next": "ar/Third Floor (4).jpg"
      },
      {
        "pitch": -10.049658082833316,
        "yaw": -179.20818097823687,
        "next": null
      }
    ]
  },
  "ar/Third Floor (7).jpg": {
    "pano": "ar/Third Floor (7).jpg",
    "label": "Third Floor C Block right Middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -0.6754925740135376,
        "yaw": -1.351172979007308,
        "next": "ar/Third Floor (12).jpg"
      },
      {
        "pitch": -0.2833796040666411,
        "yaw": -175.15681385131234,
        "next": "ar/Third Floor (17).jpg"
      }
    ]
  },
  "ar/Third Floor (4).jpg": {
    "pano": "ar/Third Floor (4).jpg",
    "label": "Third Floor B and C block Bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -10.122918204181964,
        "yaw": 175.64629099527588,
        "next": "ar/Third Floor (13).jpg"
      },
      {
        "pitch": -6.819272713983608,
        "yaw": -3.4100903085862004,
        "next": "ar/Third Floor (17).jpg"
      }
    ]
  },
  "ar/Third Floor (17).jpg": {
    "pano": "ar/Third Floor (17).jpg",
    "label": "Third Floor C Block right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -5.957622569057351,
        "yaw": -43.29629306700093,
        "next": "ar/Third Floor (4).jpg"
      },
      {
        "pitch": -6.724053061737705,
        "yaw": 38.84685376081646,
        "next": "ar/Third Floor (7).jpg"
      }
    ]
  },
  "ar/Third Floor (20).jpg": {
    "pano": "ar/Third Floor (20).jpg",
    "label": "Third Floor C block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -18.432351748483885,
        "yaw": 87.59832413135216,
        "next": "ar/Third Floor (5).jpg"
      },
      {
        "pitch": -8.49641238825768,
        "yaw": 2.984654599654019,
        "next": "ar/Third Floor (16).jpg"
      }
    ]
  },
  "ar/First Floor (20).jpg": {
    "pano": "ar/First Floor (20).jpg",
    "label": "First Floor B Block Right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -21.618074665890937,
        "yaw": -125.39503542652699,
        "next": "ar/1BM.jpg"
      },
      {
        "pitch": -9.551526409047923,
        "yaw": 43.13132669186063,
        "next": "ar/First Floor (19).jpg"
      },
      {
        "pitch": -8.60339673907905,
        "yaw": -37.48967193415563,
        "next": "ar/First Floor (6).jpg"
      },
      {
        "pitch": -7.8706580459838715,
        "yaw": 134.6709395048197,
        "next": "ar/1A1.jpg"
      }
    ]
  },
  "ar/First Floor (19).jpg": {
    "pano": "ar/First Floor (19).jpg",
    "label": "First Floor B Block Right Middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -5.792978791734127,
        "yaw": 179.27696272815515,
        "next": "ar/First Floor (20).jpg"
      },
      {
        "pitch": -3.79967076971804,
        "yaw": -0.3556331988478922,
        "next": "ar/First Floor (18).jpg"
      }
    ]
  },
  "ar/First Floor (18).jpg": {
    "pano": "ar/First Floor (18).jpg",
    "label": "First Floor B Block Right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -2.6109294368283185,
        "yaw": -53.52772454492202,
        "next": "ar/First Floor (19).jpg"
      },
      {
        "pitch": -2.5312339839225175,
        "yaw": 38.17697594806114,
        "next": "ar/First Floor (17).jpg"
      },
      {
        "pitch": -6.962334439401393,
        "yaw": -149.89642387361187,
        "next": "ar/First Floor (22).jpg"
      }
    ]
  },
  "ar/First Floor (17).jpg": {
    "pano": "ar/First Floor (17).jpg",
    "label": "First Floor B and C Bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -10.024595842365196,
        "yaw": 179.353012671627,
        "next": "ar/First Floor (18).jpg"
      },
      {
        "pitch": -9.268397324113398,
        "yaw": -1.493340374963084,
        "next": "ar/First Floor (16).jpg"
      }
    ]
  },
  "ar/First Floor (16).jpg": {
    "pano": "ar/First Floor (16).jpg",
    "label": "First Floor C Block Right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -15.807949004852011,
        "yaw": -46.824955841663886,
        "next": "ar/First Floor (17).jpg"
      },
      {
        "pitch": -6.481226076295339,
        "yaw": 35.566745342224166,
        "next": "ar/First Floor (15).jpg"
      }
    ]
  },
  "ar/First Floor (15).jpg": {
    "pano": "ar/First Floor (15).jpg",
    "label": "First Floor C Block Right Middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 0,
        "next": "ar/First Floor (16).jpg"
      },
      {
        "pitch": -7.096766639648999,
        "yaw": -177.902789869431,
        "next": "ar/First Floor (14).jpg"
      }
    ]
  },
  "ar/First Floor (14).jpg": {
    "pano": "ar/First Floor (14).jpg",
    "label": "First Floor C Block Right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -2.522958552020223,
        "yaw": 1.0667900072916807,
        "next": "ar/First Floor (15).jpg"
      },
      {
        "pitch": -6.018994762194357,
        "yaw": 90.57176045774068,
        "next": "ar/First Floor (6).jpg"
      }
    ]
  },
  "ar/First Floor (6).jpg": {
    "pano": "ar/First Floor (6).jpg",
    "label": "First Floor B and C block Bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -6.815735608487438,
        "yaw": -2.8626589628249697,
        "next": "ar/First Floor (20).jpg"
      },
      {
        "pitch": -7.354100080906666,
        "yaw": 178.73540619679372,
        "next": "ar/First Floor (14).jpg"
      }
    ]
  },
  "ar/First floor (21).jpg": {
    "pano": "ar/First floor (21).jpg",
    "label": "First floor c block left corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -2.3089211905165117,
        "yaw": 90.96303421106859,
        "next": "ar/First Floor (12).jpg"
      },
      {
        "pitch": -2.6632613576696946,
        "yaw": 2.2748855513094233,
        "next": "ar/1BC-1.jpg"
      }
    ]
  },
  "ar/First Floor (12).jpg": {
    "pano": "ar/First Floor (12).jpg",
    "label": "First floor c block left middle corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -6.2667182126016865,
        "yaw": -84.69053297697813,
        "next": "ar/First floor (21).jpg"
      },
      {
        "pitch": -8.277050994705395,
        "yaw": 90.93219695060768,
        "next": "ar/First Floor (13).jpg"
      }
    ]
  },
  "ar/First Floor (13).jpg": {
    "pano": "ar/First Floor (13).jpg",
    "label": "First floor c block left corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -10.204952254486788,
        "yaw": 150.8856571173251,
        "next": "ar/First Floor (12).jpg"
      },
      {
        "pitch": -14.513421335130353,
        "yaw": -122.94454334508397,
        "next": "ar/First Floor (9).jpg"
      }
    ]
  },
  "ar/First Floor (9).jpg": {
    "pano": "ar/First Floor (9).jpg",
    "label": "First floor a and c block bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -7.578977806748363,
        "yaw": 178.86876358834812,
        "next": "ar/First Floor (13).jpg"
      },
      {
        "pitch": -7.375179108976783,
        "yaw": -1.755796692123874,
        "next": "ar/First Floor (24).jpg"
      }
    ]
  },
  "a0_gate": {
    "pano": "ar/0GATE.jpg",
    "label": "Gate Enterance",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_watch_1"
      }
    ]
  },
  "a0_watch_1": {
    "pano": "ar/0WATCH.jpg",
    "label": "Enterance 1",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_watch_2"
      },
      {
        "pitch": -15,
        "yaw": 180,
        "next": "a0_gate"
      }
    ]
  },
  "a0_watch_2": {
    "pano": "ar/0WATCH1.jpg",
    "label": "Enterance pathway",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_entrance_main"
      },
      {
        "pitch": -15,
        "yaw": 180,
        "next": "a0_watch_1"
      }
    ]
  },
  "a0_entrance_main": {
    "pano": "ar/0ENTRANCE.jpg",
    "label": "The main Entrance",
    "audio": "",
    "arrows": [
      {
        "pitch": -13.315840097652144,
        "yaw": -3.4011609791527646,
        "next": "a0_entrance_1"
      },
      {
        "pitch": -15,
        "yaw": 90,
        "next": "a0_watch_2"
      },
      {
        "pitch": -15,
        "yaw": -90,
        "next": "a0_entrance_main1"
      }
    ]
  },
  "a0_entrance_main1": {
    "pano": "ar/0ENTRANCE3.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "a0_entrance_parking"
      },
      {
        "pitch": -10,
        "yaw": 90,
        "next": "a0_entrance_main"
      }
    ]
  },
  "a0_entrance_parking": {
    "pano": "ar/0PARKING.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "a0_entrance_main1"
      },
      {
        "pitch": -10,
        "yaw": 90,
        "next": "a0_entrance_ghostel"
      }
    ]
  },
  "a0_entrance_ghostel": {
    "pano": "ar/0GHOSTEL.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "a0_entrance_parking"
      },
      {
        "pitch": -10,
        "yaw": 90,
        "next": "a0_entrance_parking1"
      }
    ]
  },
  "a0_entrance_parking1": {
    "pano": "ar/0PARKING2.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "a0_entrance_power_house"
      },
      {
        "pitch": -10,
        "yaw": 90,
        "next": "a0_entrance_ghostel"
      }
    ]
  },
  "a0_entrance_power_house": {
    "pano": "ar/0POWERHOUSE.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_hospital"
      },
      {
        "pitch": -3,
        "yaw": 120,
        "next": "d0_corridor_left3"
      },
      {
        "pitch": -10,
        "yaw": 180,
        "next": "a0_entrance_parking1"
      }
    ]
  },
  "a0_entrance_1": {
    "pano": "ar/0ENTRANCE1.jpg",
    "label": "Main Entrance 1",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_entrance_2"
      },
      {
        "pitch": -15,
        "yaw": 180,
        "next": "a0_entrance_main"
      }
    ]
  },
  "a0_entrance_2": {
    "pano": "ar/0ENTRANCE2.jpg",
    "label": "Main Entrance 2",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_junction"
      },
      {
        "pitch": -15,
        "yaw": 180,
        "next": "a0_entrance_1"
      }
    ]
  },
  "a0_hospital": {
    "pano": "ar/0HOSPITAL.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -5,
        "yaw": 60,
        "next": "a0_hospital_right"
      },
      {
        "pitch": -5,
        "yaw": 120,
        "next": "a0_entrance_power_house"
      },
      {
        "pitch": -10,
        "yaw": -60,
        "next": "a0_hospital_left"
      }
    ]
  },
  "a0_hospital_left": {
    "pano": "ar/0HOSPATH.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 60,
        "next": "a0_hospital"
      },
      {
        "pitch": -10,
        "yaw": -80,
        "next": "a0_"
      }
    ]
  },
  "a0_hospital_right": {
    "pano": "ar/0HOSPATH1.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 80,
        "next": "a0_amenity_g"
      },
      {
        "pitch": -10,
        "yaw": -60,
        "next": "a0_hospital"
      }
    ]
  },
  "a0_amenity_g": {
    "pano": "ar/0AMENITYG.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 80,
        "next": "a0_"
      },
      {
        "pitch": -10,
        "yaw": -60,
        "next": "a0_hospital"
      }
    ]
  },
  "a0_junction": {
    "pano": "ar/0AM.jpg",
    "label": "The Lobby",
    "audio": "",
    "arrows": [
      {
        "pitch": -5,
        "yaw": 180,
        "next": "a0_block_bm"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_entrance_2"
      },
      {
        "pitch": -5,
        "yaw": -135,
        "next": "a0_corridor_right"
      },
      {
        "pitch": -5,
        "yaw": 135,
        "next": "a0_corridor_left"
      }
    ]
  },
  "a0_corridor_left": {
    "pano": "ar/0A-1.jpg",
    "label": "Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_block_bm"
      },
      {
        "pitch": -15,
        "yaw": 180,
        "next": "a0_corridor_left1"
      }
    ]
  },
  "a0_corridor_left1": {
    "pano": "ar/0A-2.jpg",
    "label": "Principal Office",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "a0_corridor_left"
      },
      {
        "pitch": -8.648571409969081,
        "yaw": 82.21956826469344,
        "next": "a0_corridor_left2"
      }
    ]
  },
  "a0_corridor_left2": {
    "pano": "ar/0A-3.jpg",
    "label": "Gm Office",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "b0_corridor_left2"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_corridor_left1"
      }
    ]
  },
  "a0_corridor_right": {
    "pano": "ar/0A1.jpg",
    "label": "Ground Floor Right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 180,
        "next": "a0_corridor_right1"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_block_bm"
      },
      {
        "pitch": -15,
        "yaw": 90,
        "next": "a0_"
      }
    ]
  },
  "a0_corridor_right1": {
    "pano": "ar/0A2.jpg",
    "label": "Ground Floor A Block Right Middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "a0_corridor_right"
      },
      {
        "pitch": -15,
        "yaw": 90,
        "next": "a0_corridor_right2"
      }
    ]
  },
  "a0_corridor_right2": {
    "pano": "ar/0A3.jpg",
    "label": "Ground Floor A Block Right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "b0_corridor_right2"
      },
      {
        "pitch": -15,
        "yaw": 180,
        "next": "a0_corridor_right1"
      }
    ]
  },
  "b0_corridor_right2": {
    "pano": "ar/0B3.jpg",
    "label": "Ground Floor b Block Right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "a0_corridor_right2"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_"
      },
      {
        "pitch": -15,
        "yaw": 90,
        "next": "bc0_corridor_right1"
      }
    ]
  },
  "bc0_corridor_right1": {
    "pano": "ar/0BC2.jpg",
    "label": "Ground Floor B and C block Bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 90,
        "next": "c0_corridor_right2"
      },
      {
        "pitch": -15,
        "yaw": -90,
        "next": "b0_corridor_right2"
      }
    ]
  },
  "c0_corridor_right2": {
    "pano": "ar/0C3.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 0,
        "next": "c0_corridor_right1"
      },
      {
        "pitch": -15,
        "yaw": -90,
        "next": "bc0_corridor_right1"
      }
    ]
  },
  "c0_corridor_right1": {
    "pano": "ar/0C2.jpeg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 0,
        "next": "c0_corridor_right"
      },
      {
        "pitch": -15,
        "yaw": 180,
        "next": "c0_corridor_right2"
      }
    ]
  },
  "c0_corridor_right": {
    "pano": "ar/0C1.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "d0_corridor_right"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "c0_corridor_right1"
      },
      {
        "pitch": 5,
        "yaw": 90,
        "next": "bc0_corridor_right1"
      }
    ]
  },
  "a0_block_bm": {
    "pano": "ar/0BM.jpg",
    "label": "The Miniature of RIT",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 180,
        "next": "a0_junction"
      },
      {
        "pitch": -15,
        "yaw": -135,
        "next": "a0_corridor_left"
      },
      {
        "pitch": -20,
        "yaw": 135,
        "next": "a0_corridor_right"
      },
      {
        "pitch": -5,
        "yaw": -45,
        "next": "b0_corridor_left"
      },
      {
        "pitch": -10,
        "yaw": 35,
        "next": "b0_corridor_"
      },
      {
        "pitch": 10,
        "yaw": -67,
        "next": "ar/1BM.jpg",
        "label": "Go Up to First Floor"
      }
    ]
  },
  "b0_corridor_left": {
    "pano": "ar/0B-1.jpg",
    "label": "Ground Floor B Block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -10,
        "yaw": 180,
        "next": "a0_block_bm"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "b0_corridor_left1"
      },
      {
        "pitch": -15,
        "yaw": -100,
        "next": "a0_corridor_left"
      },
      {
        "pitch": -15,
        "yaw": 100,
        "next": "bc0_corridor_left1"
      }
    ]
  },
  "b0_corridor_left1": {
    "pano": "ar/0B-2.jpg",
    "label": "Ground Floor B Block Left Carridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 180,
        "next": "b0_corridor_left2"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "b0_corridor_left"
      }
    ]
  },
  "b0_corridor_left2": {
    "pano": "ar/0B-3.jpg",
    "label": "Ground Floor B block Left Corridor ",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 100,
        "next": "a0_corridor_left2"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "b0_corridor_left1"
      },
      {
        "pitch": -15,
        "yaw": -100,
        "next": "c0_corridor_left2"
      }
    ]
  },
  "bc0_corridor_left1": {
    "pano": "ar/0BC-1.jpg",
    "label": "Ground Floor B and C block Bridge",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 90,
        "next": "c0_corridor_left"
      },
      {
        "pitch": -15,
        "yaw": -90,
        "next": "b0_corridor_left"
      }
    ]
  },
  "c0_corridor_left2": {
    "pano": "ar/0C-3.jpg",
    "label": "Ground Floor C Block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 90,
        "next": "b0_corridor_left2"
      },
      {
        "pitch": -3,
        "yaw": 0,
        "next": "c0_corridor_left"
      },
      {
        "pitch": -3,
        "yaw": -10,
        "next": "dc0_corridor_left"
      }
    ]
  },
  "c0_corridor_left": {
    "pano": "ar/0C-1.jpg",
    "label": "Ground Floor C Block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 90,
        "next": "d0_corridor_left"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "c0_corridor_left2"
      },
      {
        "pitch": -15,
        "yaw": -80,
        "next": "bc0_corridor_left1"
      }
    ]
  },
  "d0_lib": {
    "pano": "ar/0LIB.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -5,
        "yaw": 150,
        "next": "d0_corridor_left2"
      },
      {
        "pitch": -5,
        "yaw": 0,
        "next": "d0_lib1"
      }
    ]
  },
  "d0_lib1": {
    "pano": "ar/0LIB2.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -5,
        "yaw": 0,
        "next": "d0_lib2"
      }
    ]
  },
  "d0_lib2": {
    "pano": "ar/0LIB3.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -5,
        "yaw": 0,
        "next": "d0_lib"
      }
    ]
  },
  "d0_mid": {
    "pano": "ar/0D0.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": 5,
        "yaw": 170,
        "next": "d0_corridor_"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "d0_mid2"
      },
      {
        "pitch": -15,
        "yaw": 60,
        "next": "d0_corridor_left"
      },
      {
        "pitch": -15,
        "yaw": -60,
        "next": "d0_corridor_right"
      }
    ]
  },
  "d0_mid2": {
    "pano": "ar/0M.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -5,
        "yaw": 180,
        "next": "d0_mid"
      }
    ]
  },
  "d0_corridor_right": {
    "pano": "ar/0D1.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -7,
        "yaw": 180,
        "next": "d0_mid"
      },
      {
        "pitch": -15,
        "yaw": 170,
        "next": "c0_corridor_right"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "d0_corridor_left1"
      }
    ]
  },
  "d0_corridor_left": {
    "pano": "ar/0D-1.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 170,
        "next": "d0_mid"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "d0_corridor_left1"
      },
      {
        "pitch": -15,
        "yaw": -90,
        "next": "c0_corridor_left"
      }
    ]
  },
  "d0_corridor_left1": {
    "pano": "ar/0D-2.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 210,
        "next": "d0_corridor_left"
      },
      {
        "pitch": -15,
        "yaw": 30,
        "next": "d0_corridor_left2"
      }
    ]
  },
  "d0_corridor_left2": {
    "pano": "ar/0D-4.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": 0,
        "yaw": 180,
        "next": "d0_corridor_left3"
      },
      {
        "pitch": -5,
        "yaw": 170,
        "next": "dc0_corridor_left"
      },
      {
        "pitch": -5,
        "yaw": 0,
        "next": "d0_corridor_left1"
      },
      {
        "pitch": -5,
        "yaw": -10,
        "next": "d0_lib"
      }
    ]
  },
  "dc0_corridor_left": {
    "pano": "ar/0D-M.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": -90,
        "next": "d0_corridor_left2"
      },
      {
        "pitch": -15,
        "yaw": 90,
        "next": "c0_corridor_left2"
      }
    ]
  },
  "d0_corridor_left3": {
    "pano": "ar/0D-3.jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -15,
        "yaw": 180,
        "next": "d0_corridor_left2"
      },
      {
        "pitch": -15,
        "yaw": 0,
        "next": "a0_entrance_power_house"
      }
    ]
  },
  "ar/First Floor (22).jpg": {
    "pano": "ar/First Floor (22).jpg",
    "label": "First Floor A Block Right Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -9.825608379111422,
        "yaw": 173.92664491444225,
        "next": "ar/1A2.jpg"
      },
      {
        "pitch": -10.81721518403879,
        "yaw": -83.7152155237217,
        "next": "ar/First Floor (18).jpg"
      }
    ]
  },
  "ar/First Floor (23).jpg": {
    "pano": "ar/First Floor (23).jpg",
    "label": "First Floor B Block Left Middle Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -6.006063303319316,
        "yaw": -178.9688004898223,
        "next": "ar/1B-1.jpg"
      },
      {
        "pitch": -4.1149087792723575,
        "yaw": -0.2509050405163072,
        "next": "ar/First Floor (24).jpg"
      }
    ]
  },
  "ar/First Floor (24).jpg": {
    "pano": "ar/First Floor (24).jpg",
    "label": "First Floor B block Left Corridor",
    "audio": "",
    "arrows": [
      {
        "pitch": -5.767427468493365,
        "yaw": 33.22460961974435,
        "next": "ar/First Floor (23).jpg"
      },
      {
        "pitch": -11.3154363501415,
        "yaw": 119.5284050184737,
        "next": "ar/1A-3.jpg"
      },
      {
        "pitch": -6.1030423116440735,
        "yaw": -55.539151911014216,
        "next": "ar/First Floor (9).jpg"
      }
    ]
  },
  "ar/Fourth Floor (1).jpg": {
    "pano": "ar/Fourth Floor (1).jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -4.543274453504628,
        "yaw": -59.721797841958434,
        "next": "ar/Third Floor (19).jpg"
      },
      {
        "pitch": -19.946918115877498,
        "yaw": 102.8867489107929,
        "next": "ar/Fourth Floor (2).jpg"
      }
    ]
  },
  "ar/Fourth Floor (2).jpg": {
    "pano": "ar/Fourth Floor (2).jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -18.749808966822073,
        "yaw": 16.23966259270964,
        "next": "ar/Third Floor (19).jpg"
      },
      {
        "pitch": -15.731336801057415,
        "yaw": -11.439330770037612,
        "next": "ar/Fourth Floor (3).jpg"
      }
    ]
  },
  "ar/Fourth Floor (3).jpg": {
    "pano": "ar/Fourth Floor (3).jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -32.23748573843787,
        "yaw": -5.620907778077422,
        "next": "ar/Fourth Floor (2).jpg"
      },
      {
        "pitch": -17.479641162555794,
        "yaw": 156.99034957070126,
        "next": "ar/Fourth Floor (4).jpg"
      }
    ]
  },
  "ar/Fourth Floor (4).jpg": {
    "pano": "ar/Fourth Floor (4).jpg",
    "label": "",
    "audio": "",
    "arrows": [
      {
        "pitch": -13.070365537299972,
        "yaw": 94.38192547052105,
        "next": "ar/Fourth Floor (3).jpg"
      },
      {
        "pitch": -15.130288333089707,
        "yaw": 46.28165965815704,
        "next": "ar/Third Floor (19).jpg"
      }
    ]
  }
};

// Automatically assign the picture's filename to the label if left empty
Object.keys(SCENES).forEach(sceneKey => {
  const scene = SCENES[sceneKey];
  if (!scene.label || scene.label.trim() === "") {
    // Extracts the filename from the pano path (e.g., "ar/1BM.jpg" -> "1BM.jpg")
    scene.label = scene.pano.split('/').pop();
  }
});